### ISSUE TITLE
Display means of transport in DropDown menu

### ISSUE THREAD

**Issue by ByteHamster** [grote/Transportr#106]

**Comment by grote** [comment]
I am closing in on 1.1.0. Are you interested in contributing this issue?

**Comment by ByteHamster** [comment]
I would love to see this functionality but, even though I currently have holidays, I don't think I will have the time to implement it. Sorry

**Comment by grote** [comment]
Any news?

How would you implement multi-selection in the drop down menu? Looks like Android does not offer such a widget. What would you show in the drop down widget when it is not expanded?

**Comment by grote** [comment]
Maybe instead of a DropDown, a DialogFragment with a custom view could be used and just the active products are shown when the Dialog was closed?

**Comment by grote** [comment]
@ByteHamster even if you have no time for the implementation, I would appreciate your thought on how you were planning on doing it. Thanks!

**Comment by ByteHamster** [comment]
Maybe something like this? "DB Navigator" does it in a similar way.

<img src="http://i.imgur.com/3s5AlIx.jpg">

**Comment by ByteHamster** [comment]
I just noticed that Transportr did not refresh time & date when I opened the app this morning

**Comment by grote** [comment]
Haha! I love your paper mockup skillz! :)

So dialog fragment it will be. Maybe instead of showing text, I will show the selected product icons when the DialogFragment is closed, let's see...

The provider should then be added to the Fragment in #39 since this is where they will be saved across various providers.

> I just noticed that Transportr did not refresh time & date when I opened the app this morning

Strange, but this should be a different ticket then.
