### ISSUE TITLE
Favorite Stations Grid

### ISSUE THREAD

**Issue by jplitza** [grote/Transportr#136]
The release of 1.0 brought a list of favorite connections, which is a great improvement over the unused space that was on the front page before. I would, however, propose to replace them by a grid (two columns of buttons) of favorite stations instead.

They could be used in two different ways:
- A single tap on the button of a station inserts it into the currently selected field (either start or end)
- A swipe from one button/station to another (or dragging one button onto another, or drawing a line from one to another, whatever you want to call it) immediately looks up that connection, like a press on a favorited connection does right now.

As the current functionality is included in the new pattern, nothing is lost by that change. On the other hand, connections from any favorite station to any other favorite station could be looked up easily without needing 2*n! favorite connections.

**Comment by grote** [comment]
Thanks for the idea. Unfortunately, it comes a little late since the favorite connections feature is already implemented and it would be a shame to throw that away.

Also, It might still be easier for some people to just click one button rather than having to search two buttons and make the connection. Usability might not necessarily improve for everybody, although I like the feature personally.

I am thinking that that there could be an option to opt-into your feature or alternatively, have a dedicated page above Recent Trips in the drawer menu. This could also be used to allow people to delete locations from the favorites like requested in #74.

Would you be interested in developing your feature yourself?

**Comment by jplitza** [comment]
I can understand that you don't want to easily replace the just introduced feature of favorite connections. And you are right, accessibility is a feature I think about far too little. I would like the opt-in.

The dedicated view would break half of the feature (the simple-tap part) if it doesn't replicate the whole query form. And as an optional view of the front page, maybe implementing #74 in there isn't a good idea, as it would be quite hidden.

However, whichever version it should be, I fear I cannot implement it. I'm no good at developing interfaces, especially not in Java (for Android), which I haven't ever used seriously. Sorry.

**Comment by grote** [comment]
This ticket is a couple of years old, nobody picked it up and I don't have time for it, so I'll close it.

**Comment by jplitza** [comment]
On top, it's not really compatible with the new UI.
