### ISSUE TITLE
Option to find the last connection for a certain directions search

### ISSUE THREAD

**Issue by rigid** [grote/Transportr#158]
a "show last connection" option, that shows the latest train, would be handy.
although its possible to show earlier/later connections with swipe, an alternative would be good so navigation can be done with less finger movement.

**Comment by grote** [comment]
That would be a nice feature, but difficult to implement, since the API Transportr uses does not support this. So it would have to make many queries in the background to find the latest connection. But what happens in cases where there is no latest connection, but the trains go all night?
Transportr could of course stop querying when it still sees a trip at 6am, but in general making several queries in the background is not ideal and might lead to timeouts and no results returned.

**Comment by rigid** [comment]
If the service doesn't support it, your way of getting consecutive trains would be nice only if one can turn it off in the options.

It should stop querying on 0:00.

Besides that, the API really needs this feature. I suppose most services provide, don't they?

**Comment by grote** [comment]
> It should stop querying on 0:00.

Why, I know cities were last connections are at 01:00 for example.

> Besides that, the API really needs this feature. I suppose most services provide, don't they?

I think most APIs do not provide that feature. You might want to ask at the public-transport-enabler project.

**Comment by rigid** [comment]
ok, I opened https://github.com/schildbach/public-transport-enabler/issues/72
