### ISSUE TITLE
Italy: IllegalArgumentException

### ISSUE THREAD

**Issue by ppoppitz** [grote/Transportr#166]
Hey,
I choose the Italy network to find a connection in Milano (Centrale FS -> Linate Aeroport).
When pressing search, I get the following error:

> IllegalArgumentException: Unknown color: #

PS: Using Transportr 1.0.6 on cyanogenmod 13.1 in German

**Comment by grote** [comment]
Thanks for reporting!
That bug happens because, some of the transport agencies is not reporting a color for this line. However, in this case, a default color should be used. This was fixed already by the PTE update in 2678ad08361defb9901e4b3a22b1a643ad58d295 and will be in the available in the next Transportr release.

**Comment by LuccoJ** [comment]
I should have reported this too, but since Italy (ATM for Milan, specifically) was added, I've never really been able to use it for any of the routes I've tried. Not that I've tried very many. The error hasn't always been the same. I will test the next version and report if it has gone away.
