### ISSUE TITLE
Add Subte Buenos Aires (Buenos Aires Underground)

### ISSUE THREAD

**Issue by ignaciolep** [grote/Transportr#179]
Please, add Subte Buenos Aires (Buenos Aires Underground).

The Buenos Aires Underground (Spanish: Subterráneo de Buenos Aires), locally known as Subte (Spanish pronunciation: [ˈsubte], from subterráneo – 'underground' or 'subterranean') is a mass transit metro system that serves the metropolitan area of Buenos Aires, Argentina.
- Logo: https://en.wikipedia.org/wiki/Buenos_Aires_Underground#/media/File:Subte_gcba_logo.png
- Wikipedia EN: https://en.wikipedia.org/wiki/Buenos_Aires_Underground
- Wikipedia ES: https://es.wikipedia.org/wiki/Subte_de_Buenos_Aires
- Navitia: https://navitia.opendatasoft.com/explore/dataset/ar/table/?sort=type_file
- OpenStreetMap "Subte de Buenos Aires" network: http://overpass-turbo.eu/s/fBv

Thanks,
Ignacio

**Comment by grote** [comment]
Hey @ignaciolep,

thanks for your nice feature request! Adding Subte Buenos Aires is quite easy since it is supported by Navitita already.

However, before it can be added to Transportr, it needs to be added to the public-transport-enabler as described here: https://transportr.grobox.de/#add_region

Do you know any Java and could maybe do that yourself?

For the logo, it would be nice if this would also be available as a vector graphic as we are currently changing all raster logos to vector graphics (SVG).

**Comment by ascuccaro** [comment]
I think it'd be better to add the whole Buenos Aires transport system, since it's all there, in the Navitia link. And, it would have the logo already, since the city has one in SVG format ([see here](https://commons.wikimedia.org/wiki/File:Escudo_de_la_Ciudad_de_Buenos_Aires.svg)). I will try to add the city to the public transport enabler library, but I'm not very familiar with Java. Maybe I can get some help from a couple of friends.

**Comment by grote** [comment]
There is an open PR with public transport enabler here: schildbach/public-transport-enabler#105

**Comment by ascuccaro** [comment]
Oh, I see. All that's left is to wait then?

**Comment by grote** [comment]
Well, it is not merged yet. Maybe you can help to improve it. And afterwards, we will need to add it to Transportr.

**Comment by grote** [comment]
This ticket is quite old and nobody took it up. I am not living in this country and can't do it. Let's close it until someone has added support for this country in public transport enabler.

As a reminder, the process for adding support for a new region is described on the homepage: https://transportr.app/contribute/#translating-into-your-language
