### ISSUE TITLE
Choose city not agency

### ISSUE THREAD

**Issue by Airon90** [grote/Transportr#187]
I think it is better not to choose the transport agency but the city itself. I use Transportr in Milan (Italy) and I don't want to see places in other cities (Rome, ...) as it could be that a station (e.g. "Repubblica") is present not only in Milan but also elsewhere ("Repubblica" is available in Rome and Bologna too).

**Comment by grote** [comment]
I don't like it as well, but this comes from Navitia. They are making the regions so big and even want to do a world-wide region. In bigger countries like the US, they at least do one region per state, but in Brazil which is much bigger than Italy, they also have only one region for the whole country.

Please take this up with them since there's nothing I can do about it.

**Comment by Airon90** [comment]
Ok, thank you very much :)
