### ISSUE TITLE
Dialogs have Light Background in Dark Theme

### ISSUE THREAD

**Issue by kas70** [grote/Transportr#209]
![screenshot_20160704-163956](https://cloud.githubusercontent.com/assets/922628/16564128/1c3573ba-4206-11e6-9e7f-a10bb4818470.png)

**Comment by grote** [comment]
Ups, looks like the dialog is not using the proper theme. Should be a simple fix. Wanna do it?

**Comment by kas70** [comment]
This only happens in the recent release. Must be caused by some change since the 1.1.2 release.
Date- and time-picker are also affected by this.
I'll finish my pull request first;)

**Comment by grote** [comment]
Oh shit in this case it might be more complicated to fix and caused by changed in the Android libraries.

**Comment by grote** [comment]
I looked into this and couldn't find a solution. There doesn't seem to be an issue reported with Google, yet.

This in `Base.V7.Theme.AppCompat.Dialog` might cause the white background:
```xml
<item name="android:colorBackground">?attr/colorBackgroundFloating</item>
```
Because `colorBackgroundFloating` seems to be set to `#ffffff`.

Maybe we need to override the background manually...

**Comment by grote** [comment]
To clarify: This is been fixed in the code by downgrading the Android support libraries again. The fix will only come into effect in the next release though.
