### ISSUE TITLE
Sweden stopped working 1.0.6 -> 1.1.0

### ISSUE THREAD

**Issue by clacke** [grote/Transportr#221]
I have been working around this problem by just staying on 1.0.6, but I accidentally upgraded and now 1.0.6 is gone from F-Droid.

When searching for connections in Sweden, there are no hits at all. I have been trying Östergötland/Linköping stops and Stockholm stops.

**Comment by clacke** [comment]
1.1.3 works. Carry on. Never mind me.

**Comment by ahstro** [comment]
Had this same problem, so for those who might still be experiencing problems: Clear the apps data/cache, worked for me.

**Comment by clacke** [comment]
Ok, I'll try that. This has happened again since then. Maybe it was the upgrade that time that cleaned something and resolved things.

**Comment by grote** [comment]
> Clear the apps data/cache, worked for me.

The only reason I can think of why this might work is that you are using saved locations to do the query, but the provider does not recognize those saved locations anymore, because they maybe changed their internal IDs.

So it would be interesting to know if it works with fresh locations that come from the auto-completion.

Also, it would help to know what the *exact* error is you guys are getting.

**Comment by clacke** [comment]
The error I got was that it couldn't find any routes. Your hypothesis sounds likely, that I was using a cached location that no longer had the same id.

I'm pretty sure I got the locations through auto-complete, but doesn't it cache that as well?

**Comment by grote** [comment]
The cached locations in the auto-complete have a star icon. Check if the others work.

So at the moment, the provider works?

**Comment by clacke** [comment]
Works. (v1.1.7) But I think it broke and came back in the last two months.
Sorry for being unresponsive.

Will try to use Transportr more, and see if this shows up again, and keep in mind the things to try.
