### ISSUE TITLE
[Feature Request]:  Please integrate Osmand for Mapview

### ISSUE THREAD

**Issue by Mannshoch** [grote/Transportr#224]
I normaly use [Osmand](https://github.com/osmandapp/Osmand) and also have downloaded tiles. Please allow to use their Maps and get station names by tip on their name.

**Comment by grote** [comment]
Hi @Mannshoch, I am using Osmand as well and would like to use their tiles, but I am going to close this issue, because before this can be worked on in Transportr, OsmAnd would need to make using their tiles possible.

Transportr uses the osmdroid library which already shares the tiles with other apps using that library.
