### ISSUE TITLE
Nearby stations isn't working in NVV/RMV

### ISSUE THREAD

**Issue by jreinert** [grote/Transportr#247]
Nothing is shown in the results. No error shown either.

**Comment by grote** [comment]
Works for me. What did you enter?

However, if there is an issue, it is most likely with the public transport enabler library and not with Transportr.

**Comment by jreinert** [comment]
I tried both, with current location and an address. It seems to work only when you input a station. Which kind of defeats the purpose.

**Comment by grote** [comment]
I tried with a station.

So, like I said, there's nothing that can be done within Transportr to fix this. It needs to be reported against and fixed in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/). Once fixed there, it will be fixed in Transportr automatically, when the library gets updated.
