### ISSUE TITLE
Add delay times to Sydney

### ISSUE THREAD

**Issue by megaminxwin** [grote/Transportr#295]
This app is nearly perfect, however I can't help noticing that delays for Sydney aren't currently available. This is rather irritating, since it means that I have to use TripView for the time being - not a bad app, but closed-source.

If you could add delay times to Sydney, that would be greatly appreciated. Thanks!

**Comment by SkyWheel** [comment]
I'm agree. I love Transportr, but for transport real-time tracking I have to use TripGo or Arrivo Sydney.

**Comment by SkyWheel** [comment]
Here is a link for NSW Transport API: https://opendata.transport.nsw.gov.au/
Unfortunately, I'm not a developer. But I would like to support transport real-time tracking in the Transportr.

**Comment by grote** [comment]
Thanks for reporting this!

Unfortunately, this is not actually related (directly) to Transportr. It is an issue you need to report to public-transport-enabler, because this is the library Transportr uses to provide public transport data. When it gets implemented there, it will automatically be included in the next version of Transportr. This is why I will close this ticket, as there's nothing to be done for Transportr.
