### ISSUE TITLE
Alias names for Favorite Locations

### ISSUE THREAD

**Issue by logos88** [grote/Transportr#320]
Hi. It would be nice to have the option to edit and delete my favourites. Currently some of my near bus stations have a quite large name and they start with the same name of the street and it would be great to be able to edit the name of the bus stations to one which would be easier fo me to know which one is it (for instance with the name "Bus in front of the Gym", etc).
Maybe a new section down of the Preferences one with a star icon and the name favourites could be a good option. So inside it you could see all your favourites and rename them or delete them as you want.
Another great option would be to select for each favourite which buses or metros do you want to know about in next exits for instance. This way, if in the bus stations there are 5 different bus, but you only care about one, you could unselect the other 4 and only see info from that one.

**Comment by grote** [comment]
Thanks for the proposal. It seems to mainly be about alias names for favorite locations, so I edited the title accordingly.

**Comment by motatuc** [comment]
I second that with/enhancement. After saving a lot of favorites it's getting hard to remember which destination they belong to...

**Comment by grote** [comment]
This ticket is quite old and nobody has worked on it until now. I personally don't have time to work on it in the foreseeable future. Since there are many other open tickets, let's close this one until someone is interested in the implementation.

> It would be nice to have the option to edit and delete my favourites. 

We have #74 for deleting these locations.

Also, I think #464 will make it easier to distinguish between locations with long names.
