### ISSUE TITLE
Where does the data of my transport network come from?

### ISSUE THREAD

**Issue by frankenpfalz** [grote/Transportr#332]
I'm new here and hope this is the right place for my issue.
I have identified some errors regarding the departures in my home transport network at Transportr.
I am located in the network "BEG (Bayern, Würzburg, Regensburg)". Some bus routes are not displayed correctly.
Can somebody tell me how the data of the transport network of Würzburg (VVM) comes to Transportr? I want to understand it so I can help to make the data and the app more accurate.

**Comment by patkan** [comment]
Hi @frankenpfalz. Thank you for asking.
First of all, Transportr shares its "backend" with other project in the form of [public-transport-enabler](https://github.com/schildbach/public-transport-enabler). Except for some legacy-provider all Provider-adapter are kept in this other repository.
So depending on what is the problem here, it might be the best thing to create an issue over there. (You can reference this issue)

Now to your problem: What exactly is your problem? Are some routes not displayed at all or are there real errors?
The backend that the provider uses can be found in line https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/BayernProvider.java#L49
This is directly the information system of BEG. So if this is a case of wrong data it is likely that the data is already coming like this from BEG.

To narrow this down you could also try the networks VVM or DB. If the errors are there also I would say they come from your public transport agency.

**Comment by frankenpfalz** [comment]
Thank you for your answer. Now I understand the background much better.
Indeed I think that the problems are coming directly from the network VVM because it's the same on bayern-fahrplan.de
I will have a look at PTE to lern more about it and maybe help to improve it.
 
-----Ursprüngliche Nachricht-----
 Von: "Patrick Kanzler" [notifications@github.com]
 Gesendet: Di. 28.03.2017 14:31
 An: "grote/Transportr" [Transportr@noreply.github.com]
 Kopie: "frankenpfalz" [m-stahl@freenet.de],  "Mention" [mention@noreply.github.com]
 Betreff: Re: [grote/Transportr] Where does the data of my transport network come from? (#332)

Hi @frankenpfalz. Thank you for asking.
 First of all, Transportr shares its "backend" with other project in the form of public-transport-enabler. Except for some legacy-provider all Provider-adapter are kept in this other repository.
 So depending on what is the problem here, it might be the best thing to create an issue over there. (You can reference this issue)
Now to your problem: What exactly is your problem? Are some routes not displayed at all or are there real errors?
 The backend that the provider uses can be found in line https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/BayernProvider.java#L49
 This is directly the information system of BEG. So if this is a case of wrong data it is likely that the data is already coming like this from BEG.
To narrow this down you could also try the networks VVM or DB. If the errors are there also I would say they come from your public transport agency.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
-----Ursprüngliche Nachricht Ende-----


---
Mit freenetmail sicher kommunizieren! Wir garantieren Ihnen verschlüsselte Datenübertragung & Datenspeicherung auf deutschen Servern - E-Mail made in Germany!
