### ISSUE TITLE
False Database Value

### ISSUE THREAD

**Issue by Pascal3366** [grote/Transportr#347]
The database seems to be outdated 
Wie were at a bus stop where a bus should drive.
But thats outdated.
Also station names are multiple for different cities but without a City Name.

**Comment by grote** [comment]
Could you please clarify the nature of your problem?

**Comment by Pascal3366** [comment]
The APP only shows the station`s Name but not the City, the station belongs to
So there were 2 stations and transporter guided us to the wrong Station in the wrong City...

**Comment by patkan** [comment]
Hi @Pascal3366, unfortunately your issue is lacking relevant information. You do not tell us the network that you are using. Without this (and even better the names of the stops) there is nothing that can be done.

The name-issue that you describe sounds like #324.
Apart from that outdated directions are likely not coming from Transportr. This incorrect routing data is probably caused by the provider. In this case you would have to contact your provider and request the routing information to be updated.

**Comment by grote** [comment]
Closing as there was no response in a long time.
