### ISSUE TITLE
Please add TransLink (Brisbane, Australia)

### ISSUE THREAD

**Issue by zayuim** [grote/Transportr#355]
Not a programmer but I would like to see Brisbane Australia added to the app. IDK how hard this is.

Here it is on [Navitia](https://navitia.opendatasoft.com/explore/dataset/au/information/?sort=type_file) and on the [site itself](https://translink.com.au/about-translink/open-data).

Again, I don't know how to program I'm sorry. But at least the data is there in GTFS.

**Comment by grote** [comment]
@pserwylo I think this one should be easy to do now where your provider has been merged into PTE, right?

**Comment by pserwylo** [comment]
@grote - Yes, this is working in PTE now, as of my changes getting merged upstream then some months ago. All of Australia is included. It can get a bit clunky (e.g. if I search for "Richmond" which is a big station in Melbourne, I get two ambiguous results, because there is also a big place called "Richmond" elsewhere in Australia). However despite that, it seems very usable to me.
