### ISSUE TITLE
Scope of networks and providers

### ISSUE THREAD

**Issue by thony8** [grote/Transportr#364]
Hi!
Transportr use various providers to get transport networks but for some countries (like France, Belgium or Italy) the provider offer several networks (ex: FR-SE -> SNCF, TCL, TAG, MTM ...) but you can also find a provider for one network or a smaller area (like german or austrian networks)
Many transport companies offer now an open data access and there are many provider services in the internet to simplify the use of the data (Navitia, Transit.land ...), is it still relevant to have "big providers" that manage several networks if it exists GTFS or API for each of these networks?

**Comment by grote** [comment]
Sorry, I don't fully get your question or what this issue is about. The providers are essentially users of an API. They provide whatever the API provides. Sometimes that is a very small region with one transport company and sometimes it is a huge region with many companies.

Transport itself doesn't use GTFS or other open data formats directly (#126). It needs an API, so all depends on those APIs.

What do you mean by "is it still relevant"? What do you suggest to change and how?

**Comment by thony8** [comment]
Sorry if it is not clear. For example, Navitia provides a set of belgian transports via its API, but with Transit.land, it provides each belgian network separately. Is it better to Transportr to have a set of networks, or (if it is possible by API) to have individual networks?

**Comment by grote** [comment]
First of all: Transitland is neither supported by PTE (the API abstraction layer used by Transportr) nor does it provide a routing API as we need it.

On the question whether Navitia should separate Belgium into several smaller regions, that is best to be discussed with them. So far they seem to go into the opposite direction, trying to create only one global region. Transportr is just using their API as is.

I personally prefer smaller regions, especially when you can't plan trips in between the cities anyway. It is also better for finding stuff with auto-complete. But it is not up to me.
