### ISSUE TITLE
Illegal State Exception

### ISSUE THREAD

**Issue by ehussong** [grote/Transportr#374]
Trying to map between a suburb of Chicago and a location in the city I receive the following error:

IllegalStateException: cannot normalize mot='0' symbol='MD-N' name='MD-N' long='Metra Train MD-N' trainType='null' trainNum='MD-N' trainband='null'

**Comment by ehussong** [comment]
The last item should be 'trainName'. Yay autocorrect!

**Comment by grote** [comment]
Sounds like an upstream bug in PTE. Did you read https://github.com/grote/Transportr/blob/master/CONTRIBUTING.md#creating-issues ?

**Comment by ehussong** [comment]
Submitted to PTE under issue #172. https://github.com/schildbach/public-transport-enabler/issues/172

**Comment by grote** [comment]
I am closing this ticket as an upstream ticket now exists. No need to track this twice.

**Comment by sedrubal** [comment]
I think, I'm experiencing the same issue. I'm not sure how severe this issue is but it sounds like it's preventing transportr to display this single train. However, transportr doesn't show any connection. Would it be possible to display all other connections that don't produce an exception with a notification that there are more that cannot be displayed?
