### ISSUE TITLE
Reload detail page of connection to get recent data for delays?

### ISSUE THREAD

**Issue by lightonflux** [grote/Transportr#38]
If you long press on a connection and select the detail page, Liberario shows your connections page and doesn't reload, which is very handy in airplane mode.

But i can't find a way to reload the connection so i get recent delay data. Is there a way to do that, or isn't that implemented?

**Comment by amilopowers** [comment]
I asked an IT guy from my employer (SBB) if they have an API to deliver realtime data. That's their answer (in German):
-----------------------
Hallo Uli

Zur Zeit ist in Klärung, zu welchen Konditionen wer welche Informationen (u.a. Echtzeitdaten) erhält mittels eines neuen Web-Services. Die Ergebnisse erwarten wir bis ca. Ende Oktober.
Ich kann Dir heute leider noch keine Details geben, da sie mir nicht bekannt sind

OK für Dich?

Gruss
**
----------------
So they are saying that the think about what and to which conditions they'll deliver (realtime)data to 3rd parties. They will decide until the end of October.
I will ask in mid November again.
I am not shure if data from SBB would help for connections outside of Switzerland. But I can imagine that it works as well because I can lookup connections with Liberario from Bern to Berlin for example (only Switzerland activated).

**Comment by grote** [comment]
Even if they implement that eventually, support for that still has to implemented in the public-transport-enabler library.
