### ISSUE TITLE
Navitia vs other GTFS repositories like transit.land?

### ISSUE THREAD

**Issue by n76** [grote/Transportr#401]
I've noticed that transit.land has data for many more transit agencies in my area than Navitia.

And it is a little unsettling to see a feed add request to Navitia result in a response that says ["Please be advised that the creation of a new coverage on our server requires resources, so we try to make sure that the amount of requests justifies the use of those resources."](https://groups.google.com/forum/#!topic/navitia/KI2ZJ2-uWGY) To me this implies either a lack of resources or desire to cover the entire world.

In contrast, the support for adding a feed to transit.land seems quite straight forward and easy and they don't suggest that they are resource limited.

Is it possible to support transit feed providers other than Navitia? Or is this so baked into the PTE layer that it can't be easily changed?

**Comment by patkan** [comment]
The problem is that Navitia supplies routing and transitland only GTFS-feeds. In order to route with this data you would have to add a routing engine to PTE or Transportr.

If you find another provider that supplies routing and has an API than you would simply have to extend PTE with support for this API.

**Comment by patkan** [comment]
For reference: this is a duplicate of #260

**Comment by n76** [comment]
As it is a duplicate, I am closing this.

Thank you @patkan for the explanation.
