### ISSUE TITLE
[2.0.0-beta3] NYC Support / Address Search

### ISSUE THREAD

**Issue by wompydomp** [grote/Transportr#420]
First of all: Thank you so much for all the hard work! I've been using Transportr for DB in Germany and have been looking forward to Transportr supporting NYC.

- Performing a search in Transportr for Streets  / Avenue only presents results from New Jersey, none from NYC. 
- If I mark a position in Manhattan, I get an address in the form 8th Avenue 800, NYC. 
- You could have a 8th Avenue address in Manhattan (NYC) as well as in Brooklyn (NYC)
- As a first work around, it would be great to be able to hit the "pin" symbol in the search window to mark a destination manually on the map

I am updating the beta version through your f-droid channel. I am really looking forward to move around the city without using Gmaps!

**Comment by grote** [comment]
Hi, thanks for your feedback! I don't live in NYC myself, so I can't test these things and therefore rely on you.

The data for NYC comes from Navitia.io. Could you please get a token from them and test their API yourself to see where the issue is? They have documentation here: http://doc.navitia.io/#getting-started
and an API playground website that you can use to simulate Transportr queries: http://canaltp.github.io/navitia-playground/

If their queries produce the same results, you would need to talk to them so they can improve their data.

> As a first work around, it would be great to be able to hit the "pin" symbol in the search window to mark a destination manually on the map

You should be able to long press a location on the map and then select it for routing.

**Comment by grote** [comment]
I was using Transportr in NYC for a few days and it worked quite well for me. There were some other issues with bus routes. However, these were also with Navitia and need to get fixed there.
