### ISSUE TITLE
Enhancement: quicklink to near station departures in menu

### ISSUE THREAD

**Issue by techge** [grote/Transportr#421]
Hi,

I am using the 2.0.0-beta3 for 2 days now and I am really excited and happy about this project. So thanks at first.

What I am missing (as a prior 'Öffi' user) is a shortcut in the menu to reach the already included feature to find near stations and show its next departures. As far as I can see I can only reach it when looking for a actual trip route and using the menu for a station there. Am I missing something? Would you mind including such short cut in the app menu (i.e. below "settings" button)?

I hope you know, what I mean :)

Kind regards

**Comment by grote** [comment]
Hi @techge, the feature you are looking for should be accessible from the main screen. Just search for the location you are interested in. Then you should have the ability to search for nearby stations and departures at the bottom of the screen.

Please let me know if that resolves the issue for you!

**Comment by techge** [comment]
Hi,
not quite, to be honest. I know the feature you are talking about and this is the exact thing I am talking about. What I would love to have is just a short link from within the menu so that I do not need to know/ to type the destination but can just look for near stations and the departures quickly.

So this would be rather a quicklink to a function that is already inccuded. Do you think this is something you would like to include in the left-side pop-up menu?

Thanks in advance!

**Comment by grote** [comment]
Sorry, but I still don't really get what you want and what the current functionality is missing.

**Comment by techge** [comment]
Hi,

no problem, it's probably me who can not explain correctly :)

Maybe I should point out, that I am coming from the Öffi App. While I surely do not want transportr to be exactly the same, there is at least one feature I would really miss in transportr.

The "find-near-station-and-show-the-departures" feature is fine, like it is. But it is a long way to get there. I would like to have the feature just in menu

![screenshot_20180220-194706](https://user-images.githubusercontent.com/25867995/36443270-921ef95a-1678-11e8-9454-d8fffa3f108b.png)

Does this clear my point?
Thanks anyway!!!

**Comment by grote** [comment]
I guess you are essentially asking for what was in Transportr v1 already, but has been removed.

So if you want to find nearby station or departures from another station X. Why don't you enter the name in the location field (that is hidden behind the navigation drawer in your screenshot) and then select the option from the bottom sheet that appears there?

Why do you need a different screen where you would also just enter the station name?

**Comment by techge** [comment]
I never was on v1, sorry. I just recently tried the beta at once, because it was recommended by someone.

Putting in a station name is different than using location service to find out nearest station and doing its thing on its own, isn't it?

I mean, of course I can and will adapt my behaviour, if necessary and if it is decided that this solution is more useful for average user, but for me it would make sense to have a option to a) look for my location and b) show me the station and departures depending on my actual station automatically. That's what I got used to and what I liked.

**Comment by grote** [comment]
Maybe it is worth digging deeper here to see your use case and find out whether it is adequately covered by Transportr.

So you don't want to find nearby station from a known station, but from your current position? If so, the map should show your current position. There's also button on the map to zoom in to the location. You can long press this point (or any other) on the map and then find nearby stations from there. Does this help?

> show me the station and departures depending on my actual station automatically. That's what I got used to and what I liked.

What do you mean by "my actual station"?

**Comment by TheLastProject** [comment]
I do notice that you can only really reach nearby stations from the start of the app, by swiping down and then hitting the "current location" button. I noticed this pattern in Transportr 2 a lot: screens have extra functionality when swiping up and down, but there is never a clear indication this is a supported action. It is confusing at first because no other app I use uses this pattern.

I think the OP is looking for an easier way to find the "current location" button, which shows all nearby stations on the map. Perhaps it could also be visible in the home screen before swiping down? For example by adding it to the row the "go to" button is at?

![](https://i.imgur.com/r5Mf1wV.png)

**Comment by TheLastProject** [comment]
I do notice that you can only really reach nearby stations from the start of the app, by swiping down and then hitting the "current location" button. I noticed this pattern in Transportr 2 a lot: screens have extra functionality when swiping up and down, but there is never a clear indication this is a supported action. It is confusing at first because no other app I use uses this pattern.

I think the OP is looking for an easier way to find the "current location" button, which shows all nearby stations on the map. Perhaps it could also be visible in the home screen before swiping down? For example by adding it to the row the "go to" button is at?

![](https://i.imgur.com/r5Mf1wV.png)

**Comment by TheLastProject** [comment]
I do notice that you can only really reach nearby stations from the start of the app, by swiping down and then hitting the "current location" button. I noticed this pattern in Transportr 2 a lot: screens have extra functionality when swiping up and down, but there is never a clear indication this is a supported action. It is confusing at first because no other app I use uses this pattern.

I think the OP is looking for an easier way to find the "current location" button, which shows all nearby stations on the map. Perhaps it could also be visible in the home screen before swiping down? For example by adding it to the row the "go to" button is at?

![](https://i.imgur.com/r5Mf1wV.png)

**Comment by grote** [comment]
I thought BottomSheets are meanwhile a standard UI practice that most people are familiar with.

Would it help if there would be an onboarding dialog the first time a bottom sheet is shown that hints at the option of moving the sheet up and down?

> I think the OP is looking for an easier way to find the "current location" button, which shows all nearby stations on the map. 

In theory, the app should always show your current location on the main map (if available) and zoom in either to that area only or to an area that includes your favorite location.

I am hesitant to automatically search for nearby stations on the map without user interaction, because this requires network requests.

**Comment by techge** [comment]
I was a bit quiet these days because I wanted to just try around a bit. Sometimes you are just to much used to a previous application... What I realized was, that I personally just need to much steps to get to the function I need to.

I tried what you said: just use the map and your location to find nearby stations. This is a nice option, you are right, I didn't got that right. I personally prefer a list of stations (especially more useful as long as the location is not completely determined), but the current solution looks pretty nice and I probably just need to get used to it.

But even then, I would really prefer to have a shortcut in menu. I would even like to have more shortcuts than initially proposed, I realized these days. The problem is, having transportr never really closed you have to go back several times, to get to the homescreen again, which is needed to look for nearby station or connections and so on.

So what I am proposing are shortcuts in menu to:

* find nearby stations
* search for connections

Imho this would not make the app more complex and would rather increase the ux.

**Comment by grote** [comment]
> The problem is, having transportr never really closed you have to go back several times, to get to the homescreen again, which is needed to look for nearby station or connections and so on.

But, the navigation drawer is only available on the main screen, not when you are in a search or a trip. So additional menu items there wouldn't help.

> So what I am proposing are shortcuts in menu to:
>     find nearby stations

What would happen when you click on this? How would Transportr know for which station you want to search?

> search for connections

There is already an always present big red button for this. Doesn't this work for you?

**Comment by techge** [comment]
> But, the navigation drawer is only available on the main screen, not when you are in a search or a trip. So additional menu items there wouldn't help.

Oh, I didn't realized this, yet. I thought the main menu is reachable from everywhere. That is to say my proposal wouldn't help, that's true. :thinking: 

> What would happen when you click on this? How would Transportr know for which station you want to search?

I meant looking for stations nearby my actual location. I know understand, that this feature (as seen below) is only looking for station near the location currently focused.

![screenshot_20180220-194822](https://user-images.githubusercontent.com/25867995/37209996-628033f8-23a7-11e8-8be8-ab3c8d165354.png)

So as I understand it, the app is designed to be as simple as possible, what's a good thing for sure! But for me some often needed options are hidden in submenus to let the app look more simple, thus making it more difficult to handle it in everyday use. (don't want to add one or to other examples here to don't mess with this issue, maybe I open another issue)

I don't know how many people actually like the option to easily look for nearby stations and/or departures, at least I surely do. One may could add a button similar to the sticking red button used to look for a connection.

Frankly, I really don't want to look like a person persisting on its own opinion. This is just what's bothering me personally. I can understand, if you decide to keep it this way. I will learn to get used to it. But maybe it is useful for others to, don't know.

**Comment by grote** [comment]
> I meant looking for stations nearby my actual location. I know understand, that this feature (as seen below) is only looking for station near the location currently focused.

Yes, but you can focus any location on the map including your own by long tapping the map.
Please keep in mind that your current location isn't always known which is another reason adding a "shortcut" to the navigation drawer wouldn't be as easy as you think.

> One may could add a button similar to the sticking red button used to look for a connection.

I don't want to clutter the app and the map with lots of buttons. Try to keep things simple.

What I did in 1c8dd10c7a7160242775dbae9aaccbadad4d8ef7 and the latest release candidate is adding onboarding dialogs when you see this location bottom sheet for the first time, so users will know they can pull this up to discover the feature of finding nearby stations.

Something else which could be added in the future is to automatically search for nearby stations and show them on the map when you zoom in a certain area.
