### ISSUE TITLE
Add support for BC, Canada

### ISSUE THREAD

**Issue by JohnFraser3** [grote/Transportr#434]
In my understanding, everything is in place to add support for the TransLink network (and perhaps BC Transit) in British Columbia, Canada, being that the data is all available through Navitia.io. The last thing to do would be to integrate it into Transportr. That, however, I do not have the skills for. If anyone is able to work out such details it would be a great aid for us here in Vancouver wanting to use a FOSS transport app to get around.

https://navitia.opendatasoft.com/explore/dataset/ca-bc/

**Comment by grote** [comment]
Hi John,

yes your understanding is correct. Adding BC to Transportr would be easy. However, like I said in similar tickets, I can't add all these different areas myself as I barely have enough time to maintain this project. Also, somebody living there and using the provider would be in a better position to add it, because it is not just about adding it once, but also being responsible for it and maintaining it long term.

There's already an upstream pull request which did the first part of the job: schildbach/public-transport-enabler#117

You could try to ping there to get it merged. Otherwise, you could ping the people from [the PTE staging repository](https://gitlab.com/opentransitmap/public-transport-enabler) to get it added there first. Then adding it to Transportr is as simple as copying another provider like Quebec here: https://github.com/grote/Transportr/blob/master/app/src/main/java/de/grobox/transportr/networks/TransportNetworks.kt#L602-L610

**Comment by anjandev** [comment]
@grote The second part has also been done by @chimo. See: https://github.com/chimo/Transportr/commit/9df685d26581ddcce5656a735ed825929f5992e7

**Comment by grote** [comment]
The second part is outdated now though and needs to be re-done.

@anjandev if you want to help, this would be the first step:
> you could ping the people from the PTE staging repository to get it added there first.

**Comment by grote** [comment]
Great news @anjandev! Looks like it has been merged by the bot now as well.

**Comment by grote** [comment]
This got closed with #448
