### ISSUE TITLE
Bring back the simple UI 

### ISSUE THREAD

**Issue by haary** [grote/Transportr#462]
When opening Transportr 2.0 it loads a map at first and then you have to push a button to do a search . This is subotimal on older smartphones or when using networks with limited bandwith. The simple text-based UI was better for this use cases, which happenedto me quite often, when standing in the middle of nowhere with poor connectivity and wanted to know how to get home from there.

Would it be too much work, to make it an configurable option to open the simple search UI  without loading the map first, like in Transportr 1.x?

**Comment by grote** [comment]
> when standing in the middle of nowhere with poor connectivity and wanted to know how to get home from there.

You can add the home location as a shortcut on the desktop and use that instead of the Transportr icon.

**Comment by hggh** [comment]
thanks for your work on Transportr using it every day. it would be nice, if there is a setting to disable the map and show the favorite connections on bottom and show the normal "from" and "to" form above. but the new launcher shortcut is really nice!

**Comment by dkabus** [comment]
Still it would be nice to have an option to disable the map altogether.
A) The map takes up a lot of space by default. (I just want to enter where I'm going)
B) It uses data, which I really don't need. (I know, where my stations are.)
C) I find it distracting.
Please add an option to hide the map by default and show the search boxes and connections page instead.
Still love the app, your work is very much appreciated!

**Comment by grote** [comment]
> it would be nice, if there is a setting to disable the map and show the favorite connections on bottom and show the normal "from" and "to" form above.

The easiest way to achieve this would be a `Directions` launcher shortcut that just opens a blank directions screen with the favorites below. People who want to skip the map and not use Home or Work, can use this one to start Transportr.

> It wastes network bandwidth by autoloading things I don't need. Not everyone has mobile internet flat rates.

The old map used raster tiles which used more bandwidth than the new vector tiles.

> For instance maps of areas I am very familiar with are loaded every time.

These should be cached locally and not downloaded again. If not, that's a bug with the map library.

> It would be really useful to be able to switch between old and new UI via the menu. 

And who would be maintaining the *two* UIs for the years to come in their unpaid spare time?

**Comment by ort163** [comment]
First I would sincerely like to thank @grote for the app (and the OS efforts). (In the below text I mean ⋮ Vertical ellipsis as menu)


> The easiest way to achieve this would be a Directions launcher shortcut that just opens a blank directions screen with the favorites below. People who want to skip the map and not use Home or Work, can use this one to start Transportr.

In principle it is true, but you are making the user go through +1 dialog before easily searching. 

Not sure many people use map and use "Current location" to Home/Work. In my case, there is 'Stop' 3 min walk, from there is a Tram that goes every 20 min. But I prefer walking to another stop which is 6 min walk but there is a S-bahn every 5 min. In this case geolocation is unwanted. 

> The old map used raster tiles which used more bandwidth than the new vector tiles.
> These should be cached locally and not downloaded again. If not, that's a bug with the map library.

In principle this is true, but for phones with low GPU/memory loading *any* map it is a struggle. And if the first interaction with the app is slow, then the user will definitely assume app is bad. (You may ignore ratings as you do it for your own fun/satisfaction but this leads to assumption on the app quality). In the old GUI, I never ever even used the map (also my friends). We used 'transportr' as it was lightweight for older phones with low data usage.

If one goes to a location where the cache is not there or (manually) deleted from phone due to low storage, will it stop downloading the maps while making data request to get the itinerary? At that moment, I need only connection information - but not waste - share bandwidth with maps but get the train information ASAP. Will the app, automatically stop downloading maps with 'the Directions launcher' is pressed. (I have not tested, sorry).

> And who would be maintaining the two UIs for the years to come in their unpaid spare time?
I do agree this is difficult. As the leader you decide. :-)

UI interaction. This is where I think in the old app was better (sorry).



**Means of transport**
New UI: Need 2 steps to get to know what are the different 'Means of transport. Click on the menu -> "Means of Transport" -> then Select. It is also  'not visible' instantly for the user that what was selected. 
Old UI: Visible directly. One click bring up stuff.

**DEP/ARR or Time is...**
New UI: DEP -> ARR Also needs 3 clicks in the new UI.
Old UI: One click

**Swap From and To**
New UI: Menu->Swap-From-To
Old UI: One click.
Also in English language: Having "Swap From and To" is not a proper English language use. having too much text everywhere is poor for user interaction.

Clicking the menu is also very difficult as is near the top, next to "clock Now". Any small mistake then I click on the Now instead of the menu.

At the end of the day, if is your app feel free.
![step-1](https://user-images.githubusercontent.com/24358068/43073766-0622fa7a-8e7b-11e8-9346-ade4a908ca00.png)

**Comment by grote** [comment]
> In principle it is true, but you are making the user go through +1 dialog before easily searching.

I am not sure you understand my proposal. It would add a second launcher icon to your home screen that brings you directly to the search mask. Where is the extra dialog?

> But I prefer walking to another stop which is 6 min walk but there is a S-bahn every 5 min. In this case geolocation is unwanted.

The app wasn't made for you however. The idea is that it works best for the majority of people. If it doesn't work for you, you can still change the starting location. Using the current location is just the default.

> In the old GUI, I never ever even used the map (also my friends). We used 'transportr' as it was lightweight for older phones with low data usage.

You are welcome to use and maintain the v1 version. It is Free Software after all.

> UI interaction [...]

This are all for the directions search mask and should be a dedicated ticket I think. The idea here is to simplify the UI to hide actions people don't need to use often. I think an extra click for something you rarely use isn't the end of the world.

**Comment by grote** [comment]
> I am not sure you understand my proposal. It would add a second launcher icon to your home screen that brings you directly to the search mask.

This is how it is implemented on master now:

![directions_shortcut](https://user-images.githubusercontent.com/244947/43427442-e9d91858-942f-11e8-8758-8ec74515bfaf.gif)

**Comment by alexanderadam** [comment]
@grote the directions launcher is still unreleased, right?
As the other users here I would love being able to use the simple view again but somehow I still don't have the possibility in the current F-Droid release.

It would be nice to chose the old view as the regular view via settings. Because the launcher variant is not very intuitive. Or will this be possible with the new release as well?

By the way: people, that I know, using Transportr, prefered the old UI but not everyone of them has a GitHub account to support this issue here. :wink:

**Comment by grote** [comment]
> the directions launcher is still unreleased, right?

Yes, still unreleased.

> Besides from that: are the map tiles cached and saved for offline usage?

The map doesn't use tiles, but the information is cached for offline use, yes.

**Comment by ialokim** [comment]
Just for the record: Most of the issues mentioned here are now resolved by the Directions shortcut (see #485) and the new directions UI (rearranging the icons to not be hidden behind the menu anymore): #664 

The two last open complaints are reflected in #595 and #504, so I am going to close this issue in favor of the more specific ones.
