### ISSUE TITLE
Support for Massachusetts, USA Region

### ISSUE THREAD

**Issue by xeniarose** [grote/Transportr#508]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [x] I can help myself to get this feature implemented or know someone who wants to do it.
* [x] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
Transportr currently doesn't support any transportation in Massachusetts, USA

**Describe the solution you'd like**
Support for the above.

**Describe alternatives you've considered**
N/A

**Additional context**
I have a functioning PR to public-transport-enabler here:
https://github.com/schildbach/public-transport-enabler/pull/219

Transportr patch (WIP) located here (I will open a PR when ready):
https://github.com/erikuhlmann/Transportr/tree/region-mass

**Comment by grote** [comment]
Awesome @erikuhlmann! Wish everybody would work like you :)

Tiny detail about the upcoming PR: Please don't use new PNG files. These should be replaces by vector images. See #238

**Comment by fibn144** [comment]
Just to update this issue: The PR has been merged to public-transport-enabler.

Also, I've found SVG source for the PNG logo in this pull request: https://commons.wikimedia.org/wiki/File:Flag-map_of_Massachusetts.svg .
I converted it with https://a-student.github.io/SvgToVectorDrawableConverter.Web/ to get https://gist.github.com/fibn144/a99538fe80725a950e4fb7819c9da6d3 , but I don't know what I'm doing around Android development and so someone should sanity-check it because I haven't.   

Also the SVG (and therefore the converted Android XML file) is CC-BY-SA in case that is an issue, although if it is then both of its two source images are public domain, and so a close equivalent can be easily recreated and released CC0.

**Comment by ialokim** [comment]
Hi @fibn144, I think it would be nice to add this new region to Transportr as well. Are you still interested in working on this?

The flag itself would be better than the flag-map to have a simpler vector file - perhaps you could even try to simplify the paths further to get faster loading in Android?

**Comment by ialokim** [comment]
Unfortunately Massachusetts is not served by Navitia anymore, see https://github.com/grote/Transportr/issues/877#issuecomment-1751665629.
