### ISSUE TITLE
This guy ripped off the app without crediting

### ISSUE THREAD

**Issue by itzikiap** [grote/Transportr#512]
Hi, I didn't read all GPL 3 license, but from what I know, this is unacceptable.
This guy used the app code as it is but added ads, and removed any credit or mention of  original.
He also duplicated it for each country...  

https://play.google.com/store/apps/details?id=com.TransportEnCommunFrance.BusHorairesMetro.

**Comment by grote** [comment]
Thanks for the report. I wouldn't find things like this on my own. Maybe can you help reporting it to Google as a rip-off and license violation?

**Comment by itzikiap** [comment]
Done.

Thank you for the grate app and effort.

**Comment by rskikuli** [comment]
The same happened to the OSM based www.cityzenapp.co. After asking from community members to report it to Google (I avoid using the Play Store service) the app the violated the license is not on Play Store anymore. I propose you do the same.

**Comment by grote** [comment]
I've been in touch with `removals@google.com`, but they insist on detailed screenshots showing why *each* of the fake apps is a clone of Transportr. Seems they can't see that by simply looking at the screenshots in Google Play.

@itzikiap would you mind sending an email to that address with the subject `RE: [7-2733000022758] Your Request to Google` with some screenshots proofing that its a clone?

**Comment by jmaris** [comment]
I have contacted the publisher of the application in question, and in French (his native language).
I informed him of his obligations under the GPLv3 and explained that unless he makes the required changes to his application he risks it being taken down, and/or legal action.

If he responds i will post a translated copy here :)

**Comment by jmaris** [comment]
If i don't get a response i'll happily send the screenshots :)

**Comment by jmaris** [comment]
To keep you updated. The developer responded to me saying he or she would make the necessary changes as soon as possible.

I suggest giving him a couple of weeks, hopefully he will update the app to make it compliant

**Comment by grote** [comment]
@jmaris thanks for your initiative. It seems the person still hasn't made the necessary changes.

However, I am not sure that his business model can be made compliant with Transportr's license. He adds non-free libraries to the GPLv3 licensed app to generate app revenue. The resulting work is violating the GPLv3, because he can't provide a full copy of the source, because he doesn't have the source for the non-free libraries. See https://www.gnu.org/licenses/gpl-faq.en.html#FSWithNFLibs

**Comment by jmaris** [comment]
Oh dear, would you like me to get back to him ? it seems his english isn't great, i could speak to him in French if you see fit ? If not we can just report it

**Comment by grote** [comment]
If his business model is incompatible with the license, I would assume that he has very little interest in becoming compliant.

He's been reported two times already. I think Google hasn't acted on the copycat report and they ask for more "proof" in form of screenshots for the copyright violation report. (https://github.com/grote/Transportr/issues/512#issuecomment-418422270)

**Comment by israteneda** [comment]
Hello everyone, how Google Ads and GNU GPL 3 works. If I add ads to an Android application Should I credit or mention the original or can I not add ads to an Android application with a GPL 3 license?

**Comment by grote** [comment]
While this is off-topic: It depends on how you include the ads. If you use a non-GPLv3 compatible library, the resulting work is violating the GPLv3. Thus you'd use lose the right to distribute copies of the work you added ads to. See https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs

> if you want to use parts of other GPL-covered programs by other authors in your code, you cannot authorize the exception for them. You have to get the approval of the copyright holders of those programs.

If you want to earn money with other people's code, I suggest to get proper legal advise though.

**Comment by Lyokovic** [comment]
Hello,

Following the request to remove this application from Google Play Store:
https://play.google.com/stor/app/details?id=com.TransportEnCommunFrance.BusHorairesMetro

due to violating GPLv3 licenced application Transportr:
https://github.com/grote/Transportr/
https://play.google.com/store/apps/details?id=de.grobox.liberario

Here are the screenshot you requested to prove that application is the 
same with ads added on it.

Attached two zip archives, the first named original_app contains 
screenshots from the orginal GPLv3 licenced app and the second named 
violating_app contains screenshot from the violating app.

The violating application user also published other transportation 
applications based on the same source code, each of them violating the 
license. They can be found here: 
https://play.google.com/store/apps/developer?id=Public+transport+Transit+Times+-+Radio+FM 
.


Regards,

--
Vicx

**Comment by Lyokovic** [comment]
Hi,
I finally sent the screenshots to Google.
I Cc'd here the mail I sent (see my previous post).

I hope they will finally remove those apps!

**Comment by grote** [comment]
Thanks for your help @Lyokovic! Please keep us posted as they respond!

**Comment by Lyokovic** [comment]
They responded last week and the app serving Paris has been removed. However, there are still the other ones...

I'll try to explain them that they are all the same as the one they accepted to remove.

> Hello,
> 
> Thanks for reaching out to us.
> 
> In accordance with the Digital Millennium Copyright Act, we have completed
> processing your infringement notice. We are in the process of disabling
> access to the content in question at the following URL(s):
> 
> https://play.google.com/store/apps/details?id=com.TransportEnCommunFrance.BusHorairesMetro
> 
> The content will be removed shortly.
> 
> Regards,
> The Google Team

**Comment by grote** [comment]
Thanks a lot for your help and success @Lyokovic!

**Comment by breversa** [comment]
The offending app in apprently no longer on Google Play. Time to close the issue ? :)

**Comment by Lyokovic** [comment]
Yup, it seems that all the violating apps are now gone. I do not really know what happened as Google wanted screenshots for ALL the apps (which were basically the same) despite my explanations. But that's great! And you're welcome @grote, thanks for the app ;)

**Comment by grote** [comment]
Thanks to everyone who helped to resolve this!
