### ISSUE TITLE
Add option for "maximum walking time"

### ISSUE THREAD

**Issue by bisam** [grote/Transportr#533]
It would be nice to be able to allow more walking time (or less) then the default settings allow.

Other apps have a slider for it.

Also: Thanks for this amazing app! :)

**Comment by grote** [comment]
Hey thanks for the proposal!

Unfortunately, the walking speeds are fixed in the library Transportr uses. So unless someone adds more fine-grained values to the library, Transportr can't do anything here: https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/NetworkProvider.java#L60
