### ISSUE TITLE
Can't look for adresses which are not single integer number

### ISSUE THREAD

**Issue by ghost** [grote/Transportr#618]
In my city (Warsaw) there are many adresses which have numbers like 5/7 (and it does not mean apartment number in building). 

Unfortunately I cannot look for adresses like that in transportr.
![Screenshot_20190709-105606_Transportr](https://user-images.githubusercontent.com/52697678/60874920-25a64500-a239-11e9-9f99-7047576ae8d4.png)

Transportr 2.0.6 from F-Droid.
OS: LineageOS 16
Phone: Xiaomi MI MIX 2

**Comment by burbang** [comment]
Also affects adresses with letter like: <street name> 34A

**Comment by ialokim** [comment]
This problem is not on Transportr's side, but already present at the underlying server backend for Poland, navitia. See [this link](https://canaltp.github.io/navitia-playground/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2Fpl%2Fplaces%3Fq%3D5%252F7%2520Kolejowa%26) for the same result. 

I'm afraid we won't be able to do anything about it.
