### ISSUE TITLE
Map is missing required OpenStreetMap attribution

### ISSUE THREAD

**Issue by scruss** [grote/Transportr#628]
**Describe the bug**
Users of OpenStreetMap data must include attribution in their product. Transportr does not do this, and its background map — for my area [Toronto] at least — is clearly OSM-derived. The app credits the Mapbox Maps SDK in *Libraries*, but does not include OSM as one of its contributors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to map
2. Note lack of visible *© OpenStreetMap contributors* or *© Mapbox, © OpenStreetMap …* attribution

**Expected behavior**
1. Go to map
2. Note obvious and required *© OpenStreetMap contributors* or *© Mapbox, © OpenStreetMap …* attribution

Please see:

1. Mapbox Attribution guide: https://docs.mapbox.com/help/how-mapbox-works/attribution/

2. OSMF Licence and Legal FAQ, Attribution clause: https://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ#What_do_you_mean_by_.22Attribution.22.3F

**Screenshots**
n/a

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.6
 - **Device:** Google Pixel 3a
 - **Android Version:** 9

**Comment by grote** [comment]
Thanks @scruss! Pull requests are welcome!

**Comment by scruss** [comment]
Would love to, but I'm completely unfamiliar with this stack.

This, in styles.xml, might have quite a bit to do with it though -

    <item name="mapbox_uiAttribution">false</item>

https://github.com/grote/Transportr/blob/64257bf6b7054617493d950313f1fdaee4b87470/app/src/main/res/values/styles.xml#L57

**Comment by dieterdreist** [comment]
Attribution

You must include the Mapbox wordmark and attribution notice on any map that uses the Mapbox Maps SDK for Android. The SDK provides an attribution layout that includes all required information and can be customized either in xml or using the UiSettings object.

You may adjust the position of the Mapbox wordmark and attribution notice, but they must stay visible on the map. You may also change the background and text color of the attribution notice to match your design aesthetics, but all information must be legible.

You may not otherwise alter the Mapbox wordmark or text attribution notice. If you wish to move or to remove the Mapbox wordmark, please contact our sales team to discuss options available under our Enterprise plans.

GUIDE
Attribution guidelines
Learn more about what kinds of attribution Mapbox requires and why.


from https://docs.mapbox.com/android/maps/overview/

**Comment by dieterdreist** [comment]
Attribution

You must include the Mapbox wordmark and attribution notice on any map that uses the Mapbox Maps SDK for Android. The SDK provides an attribution layout that includes all required information and can be customized either in xml or using the UiSettings object.

You may adjust the position of the Mapbox wordmark and attribution notice, but they must stay visible on the map. You may also change the background and text color of the attribution notice to match your design aesthetics, but all information must be legible.

You may not otherwise alter the Mapbox wordmark or text attribution notice. If you wish to move or to remove the Mapbox wordmark, please contact our sales team to discuss options available under our Enterprise plans.

GUIDE
Attribution guidelines
Learn more about what kinds of attribution Mapbox requires and why.


see here
https://docs.mapbox.com/help/how-mapbox-works/attribution/

**Comment by ialokim** [comment]
@dieterdreist @scruss Would you be interested in providing some mockups, where exactly the attribution could be shown in different map views inside the app?

**Comment by scruss** [comment]
I can't speak for @dieterdreist, but I'm no developer or graphic artist. I've already [suggested](https://github.com/grote/Transportr/issues/628#issuecomment-519623762) a solution. Where the text goes is your problem.

You're already breaking Mapbox's TOS by using the map in this way:

> 2.11 *[you will display our required branding and attribution, including all links, when you use the Services, as outlined in our documentation; …](https://www.mapbox.com/legal/tos/#[OsOs])*

**Comment by matkoniecz** [comment]
> Thanks @scruss! Pull requests are welcome!

Note that you are simply not allowed to use OSM data without a proper attribution.

**Comment by grote** [comment]
Attribution for mapbox is shown on the About Libraries page alongside attribution for other libraries used. However, it seems that attribution for open streetmap contributors is indeed missing.

**Comment by scruss** [comment]
It needs to be on the map, though. That's the deal with using OSM/Mapbox data: you use our (free, wonderful) data, you credit us. It's not hard. Everyone else does it.

**Comment by matkoniecz** [comment]
> Everyone else does it.

This part is sadly not true, some entities (like here) are using OSM data illegally. (and there may be rare weird cases where following license is not necessary, like fair use exceptions - that almost certainly do not apply here)

**Comment by matkoniecz** [comment]
Is it released on Google Play or has something got broken?

(F-droid has currently map broken outright so missing attribution is not a problem anyway)
