### ISSUE TITLE
train color wrong (TLEM)

### ISSUE THREAD

**Issue by francescosoave** [grote/Transportr#638]
**Describe the bug**
in Tlem the color seems to be set correctly [line 101](https://github.com/schildbach/public-transport-enabler/blob/master/src/de/schildbach/pte/TlemProvider.java#L101) but it does display as red in Transporttr.

**To Reproduce**
1. Set FROM London Liverpool Street Station and To: Stoke Newington Station
2. Click on search
4. The train with long numbers (currently in red boxes) should be orange

**Expected behavior**
box background color should be orange

**Screenshots**
![Screenshot_20191021-133929](https://user-images.githubusercontent.com/26126452/67205821-6ef55b80-f408-11e9-9681-99b033f7631b.jpg)

**Versions (please complete the following information):**
 - **Transportr Version:** [latest]
 - **Device:** [Oneplus 3t]
 - **Android Version:** [9]

**Comment by grote** [comment]
Thanks for reporting this issue. Unfortunately, Transportr is not the right project as it uses the public-transport-enabler library for this functionality. The issue is most likely there. You can check if it was [reported already](https://github.com/schildbach/public-transport-enabler/issues) and if not [report it there](https://github.com/schildbach/public-transport-enabler/issues/new).

**Comment by grote** [comment]
I couldn't find line 101 or 67619 in the TLEM styles in PTE.
