### ISSUE TITLE
Consider using upstream version of `public-transport-enabler`

### ISSUE THREAD

**Issue by sideeffffect** [grote/Transportr#647]
The fork is of low quality. It does not have CI and is broken, thus prevents and/or deters contributing to Transportr

see https://github.com/grote/Transportr/pull/644#issuecomment-552138533 for details

**Comment by ialokim** [comment]
Transportr is using a forked version of PTE, because the official one usually does not accept new network providers quickly. Also refer to [the README](https://gitlab.com/opentransitmap/public-transport-enabler/blob/master/README.md) for networks which are supported additionally within the fork.

We are supposed to have a CI running for the fork but for some reason it didn't catch the variable name problem. Feel free to look into it [here](https://gitlab.com/opentransitmap/public-transport-enabler/blob/master/.gitlab-ci.yml).

I'm sorry for any inconvenience you may have encountered within the last days.
