### ISSUE TITLE
Add Working Place As Static Location

### ISSUE THREAD

**Issue by DJaeger** [grote/Transportr#70]
It should be possible to add and change the location (or multiple) of your workingplace.

**Comment by grote** [comment]
Do you mean like the home location in the drop down menu when you enter locations?

All locations are saved and presented to you as favourites sorted by the most used. So if you go to work everyday, you should soon find your work location below your home location very quickly.

**Comment by DJaeger** [comment]
Yes, I mean like home location.
Sure is it presented in the favorites, but I think it is an primary target like home location.
Think of you was on an holiday trip with multiple routings, it will take some time until you can have your working location in an so primary position like the home adress.

**Comment by grote** [comment]
With GPS and Home, there are already two special static locations and with the keyboard folded out, there's not so much space. That's why I'm very hesitant to add another static location to the list. However, I wouldn't mind a pull request that includes a preference to turn the display of this location on/off.

**Comment by grote** [comment]
We now have the possibility to save dedicated trips and show them on the start page like from home to work which can also be used to search for the return trip, so I am tempted to close this issue. What do you think?

**Comment by DJaeger** [comment]
Ok
