### ISSUE TITLE
paris RER A

### ISSUE THREAD

**Issue by grorico1** [grote/Transportr#741]
Hello,

The A RER subway line isn't suggested anymore by TransportR. It was working fine a few days ago.
Can anyone help ?

Eric.

**Comment by grorico1** [comment]
Oops ... i forgot to say that-s happening in Paris.

Eric.

**Comment by ialokim** [comment]
Hi Eric, thanks for reporting the issue. This is most likely due to some issue in the underlying data source for Paris and something that cannot be resolved within Transportr itself. Consider reporting the problem at [public-transport-enabler](https://github.com/schildbach/public-transport-enabler) which is the library used to fetch the data from Navitia.

Please also be more specific on which stations you've looked up and where exactly the subway line is missing.

**Comment by grorico1** [comment]
You're right. It's working again.
Eric.

**Comment by ialokim** [comment]
Closing as this seems to be fixed.
