### ISSUE TITLE
BVG not working, no network connection at all

### ISSUE THREAD

**Issue by dinotheextinct** [grote/Transportr#776]
**Describe the bug**
If you search for any destination or location in general, there is nothing coming up through the search when using Germany, Berlin,  BVG network.
**To Reproduce**
See above.

**Expected behavior**
It worked in the past, kinda stopped working like one month ago, when using VBB for Berlin I get results as expected, also tested on two devices.

**Screenshots**

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.2
 - **Device:** Google Pixel 4a, Sony Xperia Compact XZ
 - **Android Version:** [e.g. 8.1]

**Comment by grote** [comment]
2.1.3 is latest version, does it work with that?

**Comment by dinotheextinct** [comment]
Not available in fdroid store for me.

**Comment by soerenk** [comment]
2.1.3 is now in F-Droid (but missing on Google Play) and it worked again for me. Not sure if I had the same problem, because the description of the issue is very basic. For me with 2.1.2 version of transportr I got the HTTP Error 307 Temporary Redirect and this is because they changed the API URL: https://github.com/schildbach/public-transport-enabler/commit/20392732fa61cefae3bf2a1ab9da26d5b763227f

**Comment by grote** [comment]
It was in Google Play beta track. I promoted it to production now.

**Comment by eofoe** [comment]
I updated to Android 10 to 13 and now i have the same Problems. I can only download 1.1.9 also after adding the Repro ?
