### ISSUE TITLE
Hello, I want to add the city of: Celaya, Guanajuato, México.

### ISSUE THREAD

**Issue by corenox** [grote/Transportr#800]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [X] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [X] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [X] I can help myself to get this feature implemented or know someone who wants to do it.
* [X] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
It is a problem because there are so many routes and it is sometimes difficult to find the right one when I leave work.

**Describe the solution you'd like**
The solution I would like would be to have from the application, the routes and schedules to make it easier to transport us and help more people like me who are frustrated.

**Describe alternatives you've considered**
What I have considered is to map the routes, since I have images of the routes and to elaborate the GTFS file.

**Additional context**
I share the information available to me: 

https://celaya.gob.mx/rutastransporte/

https://www.celaya.gob.mx/RutasTransporte/RutasMejoradas.pdf

(Sorry for my English, my main language is Spanish and I am not yet fluent in English.)

**Comment by Altonss** [comment]
As stated here:



> If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

You need to ask here https://github.com/schildbach/public-transport-enabler/ to include new networks!

**Comment by ialokim** [comment]
As already mentioned, before your data can be included into Transportr, you need to add it to public-transport-enabler. As for this, you need to have your data accessible somewhere on the internet, e.g. on Navitia. For this, you will indeed need a GTFS file. Similar projects exist for other locations around the world, where routing information has been added to openstreetmap and then combined with some timetable information using https://github.com/grote/osm2gtfs. Feel free to contact me privately if you'd like some more guidance on this, but I'm going to close this issue here for now, since we cannot do anything on Transportr's side for this.
