### ISSUE TITLE
Blank map

### ISSUE THREAD

**Issue by Eirikr70** [grote/Transportr#822]
Hello, So this is my issue
I run Transportr on a Xiaomi K20 with DivestOS. Region is Paris.
When I click to see something on a map, I get a blank page with squares (probably the tiles) and the path figured on this absence of map. I authorised location but it seems unrelated. I didn't find any parameter about maps, and I use OSM for another app (Organic Maps).
Got any clue ?

**Comment by ialokim** [comment]
What version of Transportr are you using? When and how did you install it?

**Comment by Eirikr70** [comment]
Version is 1.1.9 and I installed it little before I posted. But I have blacklisted Google DNS calls. That might be the reason if you use Google Maps ...

**Comment by ialokim** [comment]
I see, unfortunately the current versions of Transportr have been [disabled from F-Droid](https://github.com/grote/Transportr/issues/668#issuecomment-1189076273) which is why you've installed this old, now unsupported version from there. We'll try to bring version 2 back to F-Droid, but in the meantime you can also download the APK from the releases page here on github and install it manually (by opening it on your Android phone): https://github.com/grote/Transportr/releases/tag/2.1.4

Be aware though that you will not get automatic updates this way and that you will need to uninstall the old version 1.1.9 before.

**Comment by Eirikr70** [comment]
Thanks. I have installed it the APK way. But what is the usual way ?

**Comment by ialokim** [comment]
We'll try to bring the current version of Transportr back to F-Droid and Google Play.
